name: AIAP Assessment 21 branch Ambady
on:
  push:
    branches:
      - Ambady
  workflow_dispatch:

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run executable bash script
        run: python ./src/main.py
      - name: Assessment 21 Reminder
        run: |
          echo "Reminder to add AISG-AIAP as a collaborator in your repository"
          echo "Once your submission is complete, fill up the form provided in the Assessment 21 document"
