name: AIAP Assessment 21 branch Ambady

on:
  push:
    branches:
      - Ambady          # runs only for Ambady pushes
  workflow_dispatch:     # manual runs: pick Ambady in the dropdown

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (triggering ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}   # ensures Ambady code when Ambady triggers

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # or 3.10/3.12 as your project needs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run executable bash script
        run: python ./src/main.py

      - name: Assessment 21 Reminder
        run: |
          echo "Reminder to add AISG-AIAP as a collaborator in your repository"
          echo "Once your submission is complete, fill up the form provided in the Assessment 21 document"
